version: '3.8'

services:
  app:
    image: url-shortener-app
    depends_on:
      - db
      - redis
    ports:
      - "8080:8080"
    environment:
      DB_USERNAME: root
      DB_PASSWORD: password
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      REDIS_HOST: redis
      REDIS_PORT: 6379

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: url_shortener_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7.2
    ports:
      - "6379:6379"

volumes:
  mysql_data: